CREATE TABLE USER_REGISTRATION
(
    ID           INTEGER      NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    COMPANY      VARCHAR(255) NOT NULL,
    ADDRESS      VARCHAR(255) NOT NULL,
    CITY         VARCHAR(255) NOT NULL,
    STATE        VARCHAR(255) NOT NULL,
    ZIP          VARCHAR(255) NOT NULL,
    COUNTRY      VARCHAR(255) NOT NULL,
    URL          VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(255) NOT NULL,
    FAX          VARCHAR(255) NOT NULL
);
